Fix/broken forum quote
csvalpha/amber-ui pull request #525
Opened 2022-05-04 19:21 UTC by Ellen-Wittingen

fix #289

2022-05-04 20:01 UTC, DrumsnChocolate commented on app/controllers/forum/categories/category/threads/thread/posts/index.js
> +          .scrollIntoView({ behavior: 'smooth', block: 'center' });
duplicate code, please simplify if you can

2022-05-04 20:08 UTC, guidojw requested changes

2022-05-04 20:08 UTC, guidojw commented on app/controllers/forum/categories/category/threads/thread/posts/index.js
> +    addquote(q) {
nit, but camelCase :)

2022-05-04 20:12 UTC, DrumsnChocolate commented
oh shucks

2022-05-04 20:13 UTC, DrumsnChocolate commented
I used intellij refactor first, but now I just did a find and replace in the project so I hope I didn't miss any now

2022-05-04 20:15 UTC, guidojw approved these changes

2022-05-04 20:26 UTC, merged

2022-05-04 20:26 UTC, DrumsnChocolate commented
I didn't want to wait for the tests because the new changes from staging were completely unrelated

2022-05-04 22:47 UTC, guidojw commented
I don't think this is working, the redirect and the scrolling

2022-05-05 13:58 UTC, Ellen-Wittingen commented
It does work for me, on my computer and my phone (both Firefox), so that is weird.

2022-05-05 15:54 UTC, guidojw commented
Hmm maybe my browser still had an old version cached, I'll try again

2022-05-05 17:09 UTC, guidojw commented
Ah yes it's working, epic!