Fix photo sorting
csvalpha/amber-ui pull request #554
Opened 2022-05-18 14:22 UTC by wilco375

Fixes #528

2022-05-18 20:33 UTC, DrumsnChocolate requested changes

2022-05-18 20:33 UTC, DrumsnChocolate commented on app/controllers/photo-albums/photo-album/photos/show.js
> +      .sortBy('exifDateTimeOriginal', 'createdAt');
can't this sorting take place in the `PhotoAlbum` model? For clarification, see `models/form/form.js`, specifically `get sortedQuestions()`.

2022-05-18 20:33 UTC, DrumsnChocolate commented on app/routes/photo-albums/photo-album/photos/show.js
> +      .sortBy('exifDateTimeOriginal', 'createdAt');
duplicate code, further support for my earlier comment

2022-05-27 13:28 UTC, guidojw approved these changes

2022-06-01 10:54 UTC, merged