Added room adverts
csvalpha/amber-ui pull request #804
Opened 2023-09-09 15:00 UTC by Ellen-Wittingen

Added room adverts. They are accessible via [http://localhost:4200/room-adverts](http://localhost:4200/room-adverts) and via the menu-item in the left sidebar.

There is also a view for unauthorized users on the public part of the website, it is accessible via [http://localhost:4200/public/room-forum](http://localhost:4200/public/room-forum) and via the menu-item "Kamerforum" in the "Over ons" dropdown.

Please also check if the English translations are proper English, as nobody except from me has looked at them so far.

Note: it requires the following amber-api branch to function properly:

2023-10-11 20:54 UTC, DrumsnChocolate requested changes
The implementation works as expected, but I see you haven't quite used ember octane. I know that lots of the entire app is still written in the old style, but please try to follow the checklist (most important): https://guides.emberjs.com/release/upgrading/current-edition/glimmer-components/
and if relevant the rest of the octane upgrade guide mentioned there.
For example, named arguments means we should be using `@roomAdvert.location` in our templates, not `roomAdvert.location`
And we should not be using `import Component from '@ember/component';` in any of our new components. Always use native classes for everything, and for components only ever extend glimmer components.

2023-10-11 21:01 UTC, DrumsnChocolate requested changes

2023-10-11 21:01 UTC, DrumsnChocolate commented on translations/en.yaml
> +    roomForum: Roomforum
```suggestion
    roomForum: Room forum
```

2023-10-21 17:04 UTC, guidojw requested changes

2023-10-21 17:04 UTC, guidojw commented on app/components/header-nav.js
> +  tagName = 'nav';
These are legacy Ember component API and Glimmer won't do anything with them. You need to wrap the stuff in the template in these accordingly: https://guides.emberjs.com/release/upgrading/current-edition/glimmer-components/#toc_outer-html

2023-10-21 17:06 UTC, guidojw commented on app/components/header-nav.js
> +  // computed('router.{currentRouteName,currentURL}'
What's up with this?

2024-05-28 19:12 UTC, DrumsnChocolate commented
The text can become rather long, and the text is not vertically bounded in display:
![afbeelding](https://github.com/csvalpha/amber-ui/assets/32799956/5daf37d0-4b3e-413e-a551-5cef49412466)

2024-05-28 19:47 UTC, DrumsnChocolate commented
![afbeelding](https://github.com/csvalpha/amber-ui/assets/32799956/bfd67543-cb8c-4265-99e7-04768eb8fabe)
When logged in, I don't see any shorttext preview of the written content of the advert. Is this something we should add?

2024-05-28 19:52 UTC, DrumsnChocolate commented
These are the main UX points I found. I will leave a code review later, this Friday evening probably

2024-06-01 20:32 UTC, Ellen-Wittingen commented
Fixed the long scrolling content. Now there is a "lees meer" button that opens a modal with a scrollable bigger view of the advert when clicked upon. That modal is also opened when clicking anywhere on the advert.

![image](https://github.com/csvalpha/amber-ui/assets/101463776/00b9d098-7219-418d-be6e-cc2353810d86)

![image](https://github.com/csvalpha/amber-ui/assets/101463776/d000221b-8a96-4ec7-95ac-45e081c9e1a1)

2024-06-01 20:33 UTC, Ellen-Wittingen commented
Fixed not showing a short description on room advert index page:

![image](https://github.com/csvalpha/amber-ui/assets/101463776/74584b69-21bb-471f-af8e-94cf78a7f68d)

2024-10-02 17:42 UTC, Ellen-Wittingen commented
Apparently I never pushed the fixes I mentioned, oops

2024-10-12 13:03 UTC, DrumsnChocolate commented
We're reviewing this once more, @lodewiges and @Notheen01 will you two also remember to leave a review before we meet on Monday?

@Ellen-Wittingen we will finally be merging this thing :)

2024-10-12 13:07 UTC, DrumsnChocolate commented
![afbeelding](https://github.com/user-attachments/assets/af95b19b-9fa6-4b63-b712-1bbf5c63e9a9)
icon doesn't load for some reason. Unsure if that's my fault

2024-10-12 13:09 UTC, DrumsnChocolate commented
yes it was my fault: I did `yarn install` in the staging branch. `yarn install` in the `feature/rooms` resolved the icon issue :facepalm:

2024-10-12 13:15 UTC, DrumsnChocolate commented
Would it be practical to have a subdomain like `kamers.csvalpha.nl` point to `csvalpha.nl/public/room-forum` ? That would allow for more external traffic, because it is easier to share and remember.

2024-10-12 14:00 UTC, DrumsnChocolate requested changes
Overall, nice work! Very happy that you adhere well to octane (as far as I can see).

Thanks Ellen! My comments in this review may not be exhaustive, so let's wait for @lodewiges and @Notheen01 reviews. The three of us will discuss them on Monday, and I'll let you know when we think this PR is ready for merging.

2024-10-12 19:08 UTC, lodewiges commented on app/components/header-nav.hbs
small question: what is the advantage of adding this. for a lot of items

2024-10-12 19:27 UTC, lodewiges reviewed
Read through it and the code looks mostly good had one comment but in the end I saw lint made the same comment

2024-10-12 19:27 UTC, lodewiges commented on app/components/header-nav.js
> +    if (!this.session.isAuthenticated && !this.media.isMobile) {
what is this checking for?

2024-10-12 19:27 UTC, lodewiges commented on app/components/public/index/header.js
> +import Component from '@ember/component';
why is this ember component and not glitter component

2024-10-12 19:27 UTC, lodewiges commented on app/templates/public/room-forum.hbs
> +  </div>
could you explain the source of this bug Monday?

2024-10-12 19:29 UTC, lodewiges commented
> Would it be practical to have a subdomain like `kamers.csvalpha.nl` point to `csvalpha.nl/public/room-forum` ? That would allow for more external traffic, because it is easier to share and remember.

sounds good lets discuss the advantages Monday

2024-10-12 19:31 UTC, lodewiges commented
staging has been updated in the meantime so we need to merge it again

2024-10-13 20:34 UTC, lodewiges commented
I am not sure if we can change this but the house name box gets recognized as address field instead of the address field itself. changing this would make it easier to fill in a advert.
![image](https://github.com/user-attachments/assets/4a25e627-be23-4819-89e5-84d317784424)

2024-10-13 20:37 UTC, lodewiges commented
it think it would be better if the date could be select through a small calender
![image](https://github.com/user-attachments/assets/7b6bcfb2-6595-4636-a632-5adc41387f72)

2024-10-13 20:46 UTC, lodewiges commented
when on the external website going to the kamerforum page, scrolling down opening a post and closing this post again.
you're unable to scroll

2024-10-13 20:48 UTC, lodewiges commented
Why did we hide the kamerforum below over ons instead of giving it its own place in the header, I thing this would be more appropriate cause people see it soon instead of needing to look in a drop down menu

2024-10-13 20:52 UTC, lodewiges commented on app/templates/public/room-forum.hbs
> +  </div>
How are you able to have the sidebar and be on the external website UI?

2024-10-13 20:54 UTC, lodewiges commented
overall looks good, some small things, style of the page is nicely inline with the rest of the site. Nice work Ellen!

2024-10-14 19:16 UTC, DrumsnChocolate commented
>it think it would be better if the date could be select through a small calender instead off text.  This also should be a required field in my opinion

I am inclined to agree

> when on the external website going to the kamerforum page, scrolling down opening a post and closing this post again.
you're unable to scroll

unable to reproduce

> Why did we hide the kamerforum below over ons instead of giving it its own place in the header, I thing this would be more appropriate cause people see it soon instead of needing to look in a drop down menu

take a look at the designs supplied by promocie. if you disagree, let's first get this merged and then have a talk to the promocie.

2024-10-18 15:16 UTC, DrumsnChocolate commented on app/templates/public/room-forum.hbs
> +  </div>
fixed

2024-10-18 15:19 UTC, DrumsnChocolate commented on app/components/header-nav.js
> +    if (!this.session.isAuthenticated && !this.media.isMobile) {
discussed in person

2024-10-18 15:27 UTC, DrumsnChocolate commented on app/components/public/index/header.js
> +    return this.images[Math.floor(Math.random() * this.images.length)];
@Ellen-Wittingen this is not used anywhere. Was this functionality finished? I presume it is meant to randomly select from a bunch of 'kamer-forum banners'?

2024-10-18 16:03 UTC, DrumsnChocolate commented
> I am not sure if we can change this but the house name box gets recognized as address field instead of the address field itself. changing this would make it easier to fill in a advert.

what browser was this again? then I can check if this happens to me too


regarding the input box for available from, I'm working on that: https://github.com/csvalpha/amber-api/pull/439
I will add changes here in ui still.

2024-10-18 16:21 UTC, lodewiges commented
it was in Microsoft edge

2024-10-19 15:34 UTC, Ellen-Wittingen commented
So everything is good, except that the "available from" field will be changed to a date instead of text by @DrumsnChocolate ? So do I still have to do anything or will you guys merge it when you are done?

2024-10-19 15:36 UTC, Ellen-Wittingen commented on app/components/forms/room-advert-form.hbs
> +    <form {{action @onSubmit on='submit'}}>
Oh, I did not see this. I just changed one back to <form {{action @onSubmit on='submit'}}> because it did not work. See my last commit

2024-10-21 07:29 UTC, DrumsnChocolate commented
> So everything is good, except that the "available from" field will be changed to a date instead of text by @DrumsnChocolate ? So do I still have to do anything or will you guys merge it when you are done?

I'll merge it when I've taken care of the remaining two points: autofill address field, and the type change of the availableFrom field.

2024-10-28 21:43 UTC, DrumsnChocolate commented
@Ellen-Wittingen I do not have any issues with the form no longer submitting when I reapply my change. Are you sure my change broke things?

2024-10-28 22:20 UTC, DrumsnChocolate commented
what am I doing lmao, that's a completely different form

2024-10-28 22:42 UTC, DrumsnChocolate commented
depends on https://github.com/csvalpha/amber-api/pull/439

2024-10-28 22:47 UTC, DrumsnChocolate approved these changes

2024-10-29 01:07 UTC, lodewiges approved these changes

2024-10-29 10:47 UTC, merged