Refactor: `{{action}}` helper usage, the sequel
csvalpha/amber-ui pull request #896
Opened 2024-11-03 22:56 UTC by DrumsnChocolate

bases on #635

2024-11-09 00:04 UTC, DrumsnChocolate commented
I initially began rewriting components to glimmer when I encountered them, but that's quite a lot of work and not strictly related to the task this PR is really meant for. I've found it more efficient to just refactor all action helpers and leave other non-octane things as they are for now. We can tackle them in other PRs.

I've also not tested that every action occurrence I've refactored in in this PR still functions properly. Not yet at least. I did test that for #635 , but I figured it's more efficient to first rewrite, and then go through all the rewrites and test their functioning.

2024-11-09 15:26 UTC, DrumsnChocolate commented
also fixes some styling in the print-enrolled component.
before:
![afbeelding](https://github.com/user-attachments/assets/91d55262-081e-473e-ac93-4c513cc3a11b)

after:
![afbeelding](https://github.com/user-attachments/assets/20d8fec8-fdda-4e19-8f5c-4faa21452058)
not perfect but quick win

2025-02-17 18:28 UTC, lodewiges requested changes
LGTM 

i think you forgot 4 files
app/components/advertisement-tool.js
app/components/boolean-tag.js
app/components/cards/activity-card.js
app/components/cards/photo-album-card.js
when these are updated i will aprove

2025-03-09 19:31 UTC, lodewiges approved these changes

2025-03-09 22:54 UTC, merged